"""Replay a converted motion npz in mjlab without running a policy.

This script mirrors ``frog_lab/scripts/mimic/replay_npz_frog.py``: it expects
NPZ files generated by ``csv_to_npz.py`` (directly or via the config-driven
front end ``config_csv_to_npz.py``) and auto-selects the robot from the
``robot_name`` field stored in the NPZ. The root body is located through the
``root_link_name`` / ``body_names`` metadata.

Example:
    python scripts/mimic/replay_npz.py \
        --motion_file source/frog_mjlab/frog_mjlab/tasks/mimic/config/g1/motions/dance1_subject2.npz
"""

from __future__ import annotations

import argparse
import signal
import time
from pathlib import Path

import numpy as np
import torch

parser = argparse.ArgumentParser(
  description="Replay converted motions with the matching robot / mimic task."
)
parser.add_argument("--motion_file", type=str, required=True, help="Path to the motion npz file.")
parser.add_argument(
  "--task",
  type=str,
  default=None,
  help="Optional mimic task id override (otherwise resolved from the npz robot_name).",
)
parser.add_argument("--device", type=str, default=None)
parser.add_argument("--num_envs", type=int, default=1)
parser.add_argument("--fps", type=float, default=None, help="Override the npz playback fps.")
parser.add_argument("--speed", type=float, default=1.0)
parser.add_argument("--frame_rate", type=float, default=60.0)
parser.add_argument(
  "--no_loop",
  action="store_false",
  dest="loop",
  default=True,
  help="Stop at the end of the motion instead of looping.",
)
args_cli = parser.parse_args()

from mjlab.envs import ManagerBasedRlEnv
from mjlab.tasks.registry import load_env_cfg
from mjlab.tasks.tracking.mdp import MotionCommandCfg
from mjlab.utils.torch import configure_torch_backends
from mjlab.viewer import NativeMujocoViewer

# ---------------------------------------------------------------------------
# Robot -> mimic task registry (the npz ``robot_name`` drives the selection).
# ---------------------------------------------------------------------------
_ROBOT_TASK_REGISTRY = {
  "g1": "FrogMjlab-G1-Mimic",
  "g1_23": "FrogMjlab-G1-23Dof-Mimic",  # frog_lab alias
  "g1_23dof": "FrogMjlab-G1-23Dof-Mimic",  # frog_mjlab name
}


def _resolve_task_id(robot_name: str, override: str | None) -> str:
  if override is not None:
    return override
  try:
    return _ROBOT_TASK_REGISTRY[robot_name]
  except KeyError as exc:
    raise KeyError(
      f"Unknown robot_name '{robot_name}'. Supported: {sorted(_ROBOT_TASK_REGISTRY)}. "
      "Use --task to select a task explicitly."
    ) from exc


def _load_motion_meta(motion_file: str) -> tuple[str, str, list[str], float]:
  """Read robot / root-body metadata written by ``csv_to_npz.py``.

  The npz is expected to carry the full metadata block emitted by the
  converter (``robot_name``, ``root_link_name``, ``body_names``,
  ``joint_names``). Missing keys raise ``KeyError`` rather than silently
  falling back to a hard-coded robot/body layout. ``fps`` stays optional
  because it can be overridden on the command line.
  """
  data = np.load(motion_file, allow_pickle=True)
  try:
    for key in ("robot_name", "root_link_name", "body_names", "joint_names"):
      if key not in data:
        raise KeyError(
          f"Motion file '{motion_file}' is missing '{key}'. "
          "Re-export the motion with scripts/mimic/csv_to_npz.py."
        )
    robot_name = str(data["robot_name"][0])
    root_link_name = str(data["root_link_name"][0])
    body_names = list(np.asarray(data["body_names"]).tolist())
    fps = float(np.asarray(data["fps"]).reshape(-1)[0]) if "fps" in data else 50.0
    return robot_name, root_link_name, body_names, fps
  finally:
    data.close()


class _ZeroPolicy:
  def __init__(self, env: ManagerBasedRlEnv) -> None:
    self.env = env

  def __call__(self, obs) -> torch.Tensor:
    del obs
    return torch.zeros(self.env.action_space.shape, device=self.env.device)


class _Motion:
  def __init__(self, path: Path, device: str, root_link_name: str, body_names: list[str]) -> None:
    data = np.load(path)
    try:
      for key in (
        "body_pos_w",
        "body_quat_w",
        "body_lin_vel_w",
        "body_ang_vel_w",
        "joint_pos",
        "joint_vel",
      ):
        if key not in data:
          raise KeyError(f"Motion file '{path}' is missing key '{key}'.")

      self.fps = float(np.asarray(data["fps"]).reshape(-1)[0]) if "fps" in data else 50.0
      self.body_pos_w = torch.as_tensor(data["body_pos_w"], dtype=torch.float32, device=device)
      self.body_quat_w = torch.as_tensor(data["body_quat_w"], dtype=torch.float32, device=device)
      self.body_lin_vel_w = torch.as_tensor(
        data["body_lin_vel_w"], dtype=torch.float32, device=device
      )
      self.body_ang_vel_w = torch.as_tensor(
        data["body_ang_vel_w"], dtype=torch.float32, device=device
      )
      self.joint_pos = torch.as_tensor(data["joint_pos"], dtype=torch.float32, device=device)
      self.joint_vel = torch.as_tensor(data["joint_vel"], dtype=torch.float32, device=device)
      self.num_frames = int(self.joint_pos.shape[0])
    finally:
      data.close()

    self.body_names = body_names
    self.root_link_name = root_link_name
    if root_link_name not in body_names:
      raise ValueError(
        f"root_link_name '{root_link_name}' not found in motion bodies: {body_names}"
      )
    self.root_index = body_names.index(root_link_name)


def _write_motion_frame(
  env: ManagerBasedRlEnv, motion: _Motion, frame_id: int
) -> None:
  robot = env.scene["robot"]
  env_ids = torch.arange(env.num_envs, device=env.device, dtype=torch.long)
  root_index = motion.root_index

  root_pos = motion.body_pos_w[frame_id, root_index].repeat(env.num_envs, 1)
  root_pos = root_pos + env.scene.env_origins[env_ids]
  root_quat = motion.body_quat_w[frame_id, root_index].repeat(env.num_envs, 1)
  root_pose = torch.cat((root_pos, root_quat), dim=-1)

  root_lin_vel = motion.body_lin_vel_w[frame_id, root_index].repeat(env.num_envs, 1)
  root_ang_vel = motion.body_ang_vel_w[frame_id, root_index].repeat(env.num_envs, 1)
  root_velocity = torch.cat((root_lin_vel, root_ang_vel), dim=-1)

  joint_pos = motion.joint_pos[frame_id].repeat(env.num_envs, 1)
  joint_vel = motion.joint_vel[frame_id].repeat(env.num_envs, 1)

  robot.write_root_link_pose_to_sim(root_pose, env_ids=env_ids)
  robot.write_root_link_velocity_to_sim(root_velocity, env_ids=env_ids)
  robot.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)
  env.scene.write_data_to_sim()
  env.sim.forward()


def run_replay(args: argparse.Namespace) -> None:
  configure_torch_backends()

  import mjlab.tasks  # noqa: F401
  import frog_mjlab.tasks  # noqa: F401

  motion_path = Path(args.motion_file).expanduser().resolve()
  if not motion_path.exists():
    raise FileNotFoundError(f"Motion file not found: {motion_path}")

  device = args.device or ("cuda:0" if torch.cuda.is_available() else "cpu")

  robot_name, root_link_name, body_names, npz_fps = _load_motion_meta(str(motion_path))
  task = _resolve_task_id(robot_name, args.task)
  print(f"[INFO]: robot_name='{robot_name}' -> task='{task}'")

  env_cfg = load_env_cfg(task, play=True)
  env_cfg.scene.num_envs = args.num_envs

  if "motion" in env_cfg.commands and isinstance(env_cfg.commands["motion"], MotionCommandCfg):
    env_cfg.commands["motion"].motion_file = str(motion_path)

  env = ManagerBasedRlEnv(cfg=env_cfg, device=device, render_mode=None)
  motion = _Motion(motion_path, device=device, root_link_name=root_link_name, body_names=body_names)

  robot = env.scene["robot"]
  if list(robot.body_names) != body_names:
    print(
      "[WARN]: npz body_names do not match the robot body order; "
      "replay uses the npz order for the root body."
    )
  if root_link_name not in robot.body_names:
    raise ValueError(
      f"root_link_name '{root_link_name}' not found in robot bodies: {robot.body_names}"
    )

  fps = args.fps or (npz_fps if npz_fps > 0 else 50.0)
  frame_dt = 1.0 / (fps * args.speed)
  viewer = NativeMujocoViewer(env, _ZeroPolicy(env), frame_rate=args.frame_rate)

  interrupted = False

  def _sigint_handler(signum, frame):
    del signum, frame
    nonlocal interrupted
    interrupted = True

  prev_handler = signal.signal(signal.SIGINT, _sigint_handler)
  frame_id = 0
  try:
    viewer.setup()
    next_frame_time = time.perf_counter()
    while viewer.is_running() and not interrupted:
      _write_motion_frame(env, motion, frame_id)
      viewer.sync_env_to_viewer()

      frame_id += 1
      if frame_id >= motion.num_frames:
        if not args.loop:
          break
        frame_id = 0

      next_frame_time += frame_dt
      sleep_time = next_frame_time - time.perf_counter()
      if sleep_time > 0.0:
        time.sleep(sleep_time)
      else:
        next_frame_time = time.perf_counter()
  finally:
    viewer.close()
    env.close()
    signal.signal(signal.SIGINT, prev_handler)


def main() -> None:
  run_replay(args_cli)


if __name__ == "__main__":
  main()
